/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_androidontheway_testjni_TestJNI */

#ifndef _Included_com_demo_androidontheway_testjni_TestJNI
#define _Included_com_demo_androidontheway_testjni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_androidontheway_testjni_TestJNI
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_demo_androidontheway_testjni_TestJNI_init
  (JNIEnv *, jobject);

/*
 * Class:     com_demo_androidontheway_testjni_TestJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_demo_androidontheway_testjni_TestJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_demo_androidontheway_testjni_TestJNI
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_androidontheway_testjni_TestJNI_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
